// Try.. Catch..

// Errorless
// try {
//     let username='onkar'
//     console.log(username)
// }
// catch(err) {
//     console.log('ERROR: '+err)
// }

// Error
// try {
//     printHi();
// }
// catch(err) {
//     console.log('ERROR: '+err)
// }

// without err object
// try {
//     printHello();
// }
// catch {
//     console.log('ERROR: Function not defined!')
// }
